
PWD=$(shell pwd)
AAP_JUCE_DIR=$(PWD)/external/aap-juce

APP_NAME=OPNplug

APP_BUILD_DIR=$(PWD)
APP_SRC_DIR=$(PWD)/external/ADLplug
JUCE_DIR=$(APP_SRC_DIR)/thirdparty/JUCE

APP_SHARED_CODE_LIBS="$(APP_NAME)_artefacts/lib$(APP_NAME)_SharedCode.a lib${APP_NAME}Data.a"

PATCH_FILE=$(PWD)/aap-juce-support.patch
PATCH_DEPTH=1

NABLE_MIDI_DEVICE_SERVICE=1

METADATA_GENERATOR_CMAKE_EXTRA_FLAGS=-DADLplug_CHIP=OPN2

include $(AAP_JUCE_DIR)/Makefile.cmake-common
